//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cms_blogPopupWidget
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Headlines { get; set; }
        public string Sentence { get; set; }
        public string Image { get; set; }
        public string Form_Name { get; set; }
        public string Form_Email { get; set; }
        public string TriggerType { get; set; }
        public string DisplayRule { get; set; }
        public string PagelinkToShow { get; set; }
        public string DisplayFrequency { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Createdby { get; set; }
        public string Receivableemail { get; set; }
        public Nullable<bool> showlinkbutton { get; set; }
        public string ButtonLink { get; set; }
        public string ButtonText { get; set; }
        public Nullable<int> EmailTemplateId { get; set; }
    }
}
