//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cms_EmailTemplete
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Details { get; set; }
        public string Subject { get; set; }
    }
}
