//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cms_EmailCampaignLogs
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string DetailLogs { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> CampaignDetailId { get; set; }
        public Nullable<int> CampaignId { get; set; }
    }
}
