//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cms_CampaignDetail
    {
        public int Id { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> Recipient_tblId { get; set; }
        public string Recipient_Email { get; set; }
        public string Recipient_Name { get; set; }
        public string EmailStatus { get; set; }
    }
}
