//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cms_blogDetail
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string MetaDescription { get; set; }
        public string Slug { get; set; }
        public string CoverImage { get; set; }
        public string BlogDetails { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Createdby { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Tags { get; set; }
        public Nullable<System.DateTime> PublishingDate { get; set; }
        public Nullable<int> Blog_readTime { get; set; }
        public Nullable<int> Blog_openCount { get; set; }
    }
}
