//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int id { get; set; }
        public string EnName { get; set; }
        public string ArName { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LocationID { get; set; }
        public string AppID { get; set; }
        public Nullable<bool> GCC { get; set; }
        public Nullable<bool> StateRequired { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> createStatus { get; set; }
        public Nullable<bool> updateStatus { get; set; }
        public Nullable<bool> IsSyncWithBMS { get; set; }
    }
}
