//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EliteCMSEntities : DbContext
    {
        public EliteCMSEntities()
            : base("name=EliteCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cms_blogDetail> Cms_blogDetail { get; set; }
        public virtual DbSet<Cms_blogPopupWidget> Cms_blogPopupWidget { get; set; }
        public virtual DbSet<Cms_BlogPopUserApply> Cms_BlogPopUserApply { get; set; }
        public virtual DbSet<Cms_Campaign> Cms_Campaign { get; set; }
        public virtual DbSet<Cms_CampaignDetail> Cms_CampaignDetail { get; set; }
        public virtual DbSet<Cms_EmailCampaignLogs> Cms_EmailCampaignLogs { get; set; }
        public virtual DbSet<Cms_EmailTemplete> Cms_EmailTemplete { get; set; }
        public virtual DbSet<Cms_Manualuser> Cms_Manualuser { get; set; }
        public virtual DbSet<Cms_NewsLetter> Cms_NewsLetter { get; set; }
        public virtual DbSet<Cms_User> Cms_User { get; set; }
        public virtual DbSet<Cms_WebsiteAction> Cms_WebsiteAction { get; set; }
        public virtual DbSet<Cms_WebsiteContactus> Cms_WebsiteContactus { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<PasswordPolicy> PasswordPolicies { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TblApplication> TblApplications { get; set; }
        public virtual DbSet<TblEmployee> TblEmployees { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<Amenity> Amenities { get; set; }
        public virtual DbSet<AmenityCategory> AmenityCategories { get; set; }
        public virtual DbSet<PropertyAmenity> PropertyAmenities { get; set; }
        public virtual DbSet<PropertyListing> PropertyListings { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
    }
}
