//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordPolicy
    {
        public int ID { get; set; }
        public Nullable<int> MinCharacter { get; set; }
        public Nullable<int> MaxCharacter { get; set; }
        public Nullable<int> MinNumCharacter { get; set; }
        public Nullable<int> MaxSpecialCharacter { get; set; }
        public Nullable<bool> IsPasswordExpired { get; set; }
        public string PasswordExpiredDuration { get; set; }
        public Nullable<bool> LowerCase { get; set; }
        public Nullable<bool> UpperCase { get; set; }
        public string SpecialCharAllowed { get; set; }
    }
}
