//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyListing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyListing()
        {
            this.PropertyAmenities = new HashSet<PropertyAmenity>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string PropertyType { get; set; }
        public string ListingType { get; set; }
        public string PriceCurrency { get; set; }
        public string MainImage { get; set; }
        public string SubImage { get; set; }
        public Nullable<bool> PaymentPlanAvailable { get; set; }
        public string PaymentPlanAvailableDescription { get; set; }
        public string PropertySlug { get; set; }
        public string PropertyCategory { get; set; }
        public string DeveloperName { get; set; }
        public string HandoverDate { get; set; }
        public string PaymentPlanStructure { get; set; }
        public string PostHandoverPayment { get; set; }
        public string ConstructionStatus { get; set; }
        public string ModelUnitImages { get; set; }
        public string ServiceCharges { get; set; }
        public Nullable<bool> ShowroomAvailable { get; set; }
        public string PropertyAge { get; set; }
        public string TenancyStatus { get; set; }
        public string MortgageStatus { get; set; }
        public Nullable<bool> PreviousOwnership { get; set; }
        public Nullable<bool> TitleDeedAvailable { get; set; }
        public Nullable<decimal> RentalPrice { get; set; }
        public string PaymentTerms { get; set; }
        public string ChequesAccepted { get; set; }
        public string CommissionFee { get; set; }
        public string TenancyContractLength { get; set; }
        public string VacatingNoticePeriod { get; set; }
        public Nullable<bool> Deposit { get; set; }
        public Nullable<int> Bedrooms { get; set; }
        public string Bathrooms { get; set; }
        public string FloorLevel { get; set; }
        public string BalconyTerrace { get; set; }
        public string PropertyView { get; set; }
        public string BuiltUpArea { get; set; }
        public string ParkingSpaces { get; set; }
        public string KitchenType { get; set; }
        public string MaidsRoom { get; set; }
        public string SmartHomeFeatures { get; set; }
        public string StorageRoom { get; set; }
        public string PlotSize { get; set; }
        public string PrivateGarden { get; set; }
        public string PrivatePool { get; set; }
        public string Furnished { get; set; }
        public string UnitType { get; set; }
        public string PantryKitchen { get; set; }
        public string Washroom { get; set; }
        public string LicenseTypeSupport { get; set; }
        public Nullable<bool> SwimmingPool { get; set; }
        public string CommunityName { get; set; }
        public string City { get; set; }
        public string Neighborhood { get; set; }
        public string ProximityToMetro { get; set; }
        public string NearbyLandmarks { get; set; }
        public string SchoolHospitalProximity { get; set; }
        public Nullable<decimal> ROI { get; set; }
        public Nullable<decimal> RentalYield { get; set; }
        public Nullable<decimal> AnnualServiceCharges { get; set; }
        public string MortgageCalculator { get; set; }
        public string RentalPaymentOptions { get; set; }
        public string ListingId { get; set; }
        public string RealEstateAgencyName { get; set; }
        public string RERAPermitNumber { get; set; }
        public string PaymentMethod { get; set; }
        public string DLDTransferFee { get; set; }
        public string CoolingSystem { get; set; }
        public string PetPolicy { get; set; }
        public string TenancyContractStatus { get; set; }
        public Nullable<System.DateTime> LeaseExpiryDate { get; set; }
        public string BoostListing { get; set; }
        public string PriorityPlacement { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<decimal> OffPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> VillaBedrooms { get; set; }
        public string VillaBathrooms { get; set; }
        public string VillaParkingSpaces { get; set; }
        public string VillaFloorLevel { get; set; }
        public string VillaBuiltUpArea { get; set; }
        public string VillaMaidsRoom { get; set; }
        public string VillaDeveloperName { get; set; }
        public string VillaFurnished { get; set; }
        public string CommercialBuiltUpArea { get; set; }
        public string CommercialParkingSpaces { get; set; }
        public string CommercialFloorLevel { get; set; }
        public string CommercialDeveloperName { get; set; }
        public string CommercialFurnished { get; set; }
        public string Description { get; set; }
        public string ChequesAcceptedRental { get; set; }
        public string Status { get; set; }
        public string Property_Title_AR { get; set; }
        public string Property_purpose { get; set; }
        public Nullable<decimal> Property_Size { get; set; }
        public string Property_Size_Unit { get; set; }
        public Nullable<decimal> plotArea { get; set; }
        public string Features { get; set; }
        public Nullable<bool> Off_plan { get; set; }
        public string Portals { get; set; }
        public string Property_Description_AR { get; set; }
        public string Rent_Frequency { get; set; }
        public string offplanDetails_saleType { get; set; }
        public string offplanDetails_dldWaiver { get; set; }
        public Nullable<decimal> offplanDetails_originalPrice { get; set; }
        public Nullable<decimal> offplanDetails_amountPaid { get; set; }
        public string Videos { get; set; }
        public string Locality { get; set; }
        public string Sub_Locality { get; set; }
        public string Tower_Name { get; set; }
        public string Listing_Agent { get; set; }
        public string Listing_Agent_Phone { get; set; }
        public string Listing_Agent_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyAmenity> PropertyAmenities { get; set; }
    }
}
