//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Category { get; set; }
        public string Message { get; set; }
        public string BudgetMin { get; set; }
        public string BudgetMax { get; set; }
        public string Currency { get; set; }
        public string PageSource { get; set; }
        public string Country { get; set; }
        public string Source { get; set; }
        public string Status { get; set; }
    }
}
