//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        public int ID { get; set; }
        public Nullable<int> PERSON_TYPE_ID { get; set; }
        public string EMPLOYEE_NUMBER { get; set; }
        public string OLD_EMPLOYEE_NUMBER { get; set; }
        public Nullable<int> PAYROLL_ID { get; set; }
        public Nullable<int> PERSON_ID { get; set; }
        public string BADGE { get; set; }
        public string TITLE { get; set; }
        public string FIRST_NAME { get; set; }
        public string SECOND_NAME { get; set; }
        public string THIRD_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME_AR { get; set; }
        public string SECOND_NAME_AR { get; set; }
        public string THIRD_NAME_AR { get; set; }
        public string LAST_NAME_AR { get; set; }
        public string FULL_NAME { get; set; }
        public string FULL_NAME_AR { get; set; }
        public string NATIONAL_IDENTIFIER { get; set; }
        public string MANAGER_FLAG { get; set; }
        public string SUPERVISOR_NUMBER { get; set; }
        public Nullable<int> ORGANIZATION_ID { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public Nullable<int> POSITION_ID { get; set; }
        public Nullable<int> GRADE_ID { get; set; }
        public string NATIONALITY_CODE { get; set; }
        public string SEX { get; set; }
        public string MARITAL_STATUS_CODE { get; set; }
        public string RELIGION_CODE { get; set; }
        public string SECT { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<System.DateTime> ORIGINAL_DATE_OF_HIRE { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_TERMINATION_DATE { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string MOBILE_SMS { get; set; }
        public string MOBILE_M { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public string OFFICE_NUMBER { get; set; }
        public string INTERNAL_LOCATION { get; set; }
        public string CURRENT_FLAG { get; set; }
        public string PRIMARY_FLAG { get; set; }
        public string ASSIGNMENT_TYPE { get; set; }
        public string ASSIGNMENT_CATEGORY { get; set; }
        public string EMPLOYMENT_CATEGORY { get; set; }
        public Nullable<int> ASSIGNMENT_ID { get; set; }
        public string ASSIGNMENT_NUMBER { get; set; }
        public Nullable<int> PAY_BASIS_ID { get; set; }
        public Nullable<int> ASSIGNMENT_STATUS_TYPE_ID { get; set; }
        public Nullable<int> PEOPLE_GROUP_ID { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string PHONE_NOS { get; set; }
        public Nullable<System.DateTime> CONTRACT_END_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE_PEOPLE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE_ASSIGNMENTS { get; set; }
        public Nullable<int> BUSINESS_GROUP_ID { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> HOD { get; set; }
        public Nullable<int> EmployeeType { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<int> EducationId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactPhoneNo { get; set; }
        public string BloodGroup { get; set; }
        public string Idenitification { get; set; }
        public string Address { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public string ProfilePicName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> WorkFromHome { get; set; }
        public byte[] ProfilePic { get; set; }
        public Nullable<bool> ExcludefromTimesheet { get; set; }
        public Nullable<bool> WPS { get; set; }
        public string GlobalId { get; set; }
        public Nullable<int> WorkSite { get; set; }
        public string PostalCode { get; set; }
        public string State { get; set; }
        public Nullable<long> SectID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.DateTime> EmpDate { get; set; }
        public string MaritalStatus { get; set; }
        public string JobType { get; set; }
        public Nullable<int> ChildCount { get; set; }
        public Nullable<bool> WFamily { get; set; }
        public string DegreeHolder { get; set; }
        public Nullable<long> EmpRankID { get; set; }
        public Nullable<int> Religion { get; set; }
        public string HouseRented { get; set; }
        public string LocationID { get; set; }
        public string AppID { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public Nullable<int> OrgChartID { get; set; }
        public Nullable<bool> IsSaleman { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AccountNo { get; set; }
        public string AccountTitle { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<decimal> Target { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Session_time { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> createStatus { get; set; }
        public Nullable<bool> updateStatus { get; set; }
        public Nullable<bool> IsSyncWithBMS { get; set; }
        public string City { get; set; }
        public string PersonalEmail { get; set; }
        public string WorkFromHomeDayWise { get; set; }
        public Nullable<bool> IncludedInSupervisorEmail { get; set; }
        public Nullable<bool> IncludedInAbsentEmail { get; set; }
        public string Bio { get; set; }
        public string Position { get; set; }
        public string LinkedIn { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string WhatsappNo { get; set; }
    }
}
