//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite_Webservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Domain { get; set; }
        public string DomainUser { get; set; }
        public string UserType { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> InspectRole { get; set; }
        public string AppId { get; set; }
        public string AppInspection { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Language { get; set; }
        public string AppWiseRoles { get; set; }
        public string AppIDs { get; set; }
        public string RoleNames { get; set; }
        public string DepartmentList { get; set; }
    }
}
